In [17]:
import pandas as pd

In [18]:
demo = pd.read_csv('../Dataset - Demographic.csv')
demo.head()

,Subject_Id,Name(optional),Gender,Age,Alchohol,Smoking,Non-Veg,Exercise,Medication,Weight,Height,Body Age,BMI,FAT,Muscle %,Viscular,RM
0,S_1,Sunil,Male,37,No,No,No,No,No,72.1,173.0,47.0,24.1,34.1,25.4,6.0,1446.0
1,S_2,Pradeep,Male,47,No,No,No,Yes,Yes(Anxiety/B.P.),71.1,181.3,53.0,22.8,36.2,24.9,5.0,1422.0
2,S_3,Navita,Female,47,No,No,No,No,Yes(Thyroid),69.4,155.0,55.0,28.0,29.6,27.4,15.0,1547.0
3,S_4,Sangeeta,Female,35,No,No,No,No,No,65.8,155.0,45.0,27.4,28.7,30.3,12.0,1510.0
4,S_5,Gayatri,Female,33,No,No,No,No,No,54.2,155.0,32.0,22.6,22.7,33.8,7.0,1354.0

In [19]:
cols = demo.columns
nums = [1,9,10,11,13,14,15,16]

for i in nums:
    demo.drop(cols[i],axis=1,inplace=True)

demo = demo.rename(columns={'Subject_Id': 'ID'})
demo.fillna(demo.mean(numeric_only=True).round(1), inplace=True)

In [20]:
demo.isna().sum()

ID            0
Gender        0
Age           0
Alchohol      0
Smoking       0
Non-Veg       0
Exercise      0
Medication    0
BMI           0
dtype: int64

In [21]:
sti = pd.read_csv('./original_STI.csv')
sti.fillna(sti.mean(numeric_only=True).round(1), inplace=True)

sti.head()

,Subject_ID,Name,ANYB_PRE,ANYB_D1,ANYB_D2,ANYB_D3,ANYB_POST,OM_PRE,OM_D1,OM_D2,...,QUIT_PRE,QUIT_D1,QUIT_D2,QUIT_D3,QUIT_POST,SPINE_PRE,SPINE_D1,SPINE_D2,SPINE_D3,SPINE_POST
0,S_1,Sunil,7.8831,4.0799,5.8499,6.4838,8.2869,10.4165,7.1193,7.6344,...,6.3856,6.4128,8.1623,6.7363,6.8459,6.2798,2.3052,2.8544,2.9943,6.9963
1,S_2,Pradeep,15.0502,7.0993,6.2025,5.5136,12.4193,15.4162,8.0646,9.7902,...,17.3146,15.5327,12.7515,12.0534,17.3439,16.5494,5.2915,9.2872,11.6643,15.0804
2,S_3,Navita,5.0374,1.7018,2.2737,8.3817,5.5388,18.6759,2.9457,1.4619,...,11.6447,14.4140,16.6938,14.7691,7.3361,4.4889,2.0365,3.8817,3.8615,7.4302
3,S_4,Sangeeta,6.1393,3.4787,2.6727,3.4427,6.5910,4.7886,8.0792,5.0298,...,5.3328,15.5156,12.1585,4.2272,7.6654,3.7913,5.7312,5.0743,4.6052,12.4440
4,S_5,Gayatri,5.9663,5.2590,2.2522,4.4278,12.1938,8.6434,11.9241,7.7736,...,4.0894,5.7255,5.7677,5.2139,6.0473,5.4366,3.8828,3.7672,3.5132,6.1009

In [22]:
sti.isna().sum()

Subject_ID     0
Name           0
ANYB_PRE       0
ANYB_D1        0
ANYB_D2        0
ANYB_D3        0
ANYB_POST      0
OM_PRE         0
OM_D1          0
OM_D2          0
OM_D3          0
OM_POST        0
SHA_PRE        0
SHA_D1         0
SHA_D2         0
SHA_D3         0
SHA_POST       0
MM_PRE         0
MM_D1          0
MM_D2          0
MM_D3          0
MM_POST        0
QUIT_PRE       0
QUIT_D1        0
QUIT_D2        0
QUIT_D3        0
QUIT_POST      0
SPINE_PRE      0
SPINE_D1       0
SPINE_D2       0
SPINE_D3       0
SPINE_POST     0
dtype: int64

In [23]:
cols = sti.columns
nums = [1,3,4,5,8,9,10,13,14,15,18,19,20,23,24,25,28,29,30]

for i in nums:
    sti.drop(cols[i],axis=1,inplace=True)

sti = sti.add_prefix('sti_')
sti = sti.rename(columns={'sti_Subject_ID': 'ID'})

In [24]:
sti.head()

,ID,sti_ANYB_PRE,sti_ANYB_POST,sti_OM_PRE,sti_OM_POST,sti_SHA_PRE,sti_SHA_POST,sti_MM_PRE,sti_MM_POST,sti_QUIT_PRE,sti_QUIT_POST,sti_SPINE_PRE,sti_SPINE_POST
0,S_1,7.8831,8.2869,10.4165,7.6699,8.6703,10.6469,7.0276,6.3796,6.3856,6.8459,6.2798,6.9963
1,S_2,15.0502,12.4193,15.4162,6.7825,14.5392,19.8126,10.5221,13.0420,17.3146,17.3439,16.5494,15.0804
2,S_3,5.0374,5.5388,18.6759,4.5084,4.6154,4.8905,1.3050,2.4480,11.6447,7.3361,4.4889,7.4302
3,S_4,6.1393,6.5910,4.7886,3.0164,4.9474,5.0776,8.2496,10.1634,5.3328,7.6654,3.7913,12.4440
4,S_5,5.9663,12.1938,8.6434,9.6875,3.8072,10.2386,6.0748,4.2132,4.0894,6.0473,5.4366,6.1009

In [25]:
database = pd.merge(demo,sti, on="ID", how='inner')

In [26]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
database.head()

,ID,Gender,Age,Alchohol,Smoking,Non-Veg,Exercise,Medication,BMI,sti_ANYB_PRE,...,sti_OM_PRE,sti_OM_POST,sti_SHA_PRE,sti_SHA_POST,sti_MM_PRE,sti_MM_POST,sti_QUIT_PRE,sti_QUIT_POST,sti_SPINE_PRE,sti_SPINE_POST
0,S_1,Male,37,No,No,No,No,No,24.1,7.8831,...,10.4165,7.6699,8.6703,10.6469,7.0276,6.3796,6.3856,6.8459,6.2798,6.9963
1,S_2,Male,47,No,No,No,Yes,Yes(Anxiety/B.P.),22.8,15.0502,...,15.4162,6.7825,14.5392,19.8126,10.5221,13.0420,17.3146,17.3439,16.5494,15.0804
2,S_3,Female,47,No,No,No,No,Yes(Thyroid),28.0,5.0374,...,18.6759,4.5084,4.6154,4.8905,1.3050,2.4480,11.6447,7.3361,4.4889,7.4302
3,S_4,Female,35,No,No,No,No,No,27.4,6.1393,...,4.7886,3.0164,4.9474,5.0776,8.2496,10.1634,5.3328,7.6654,3.7913,12.4440
4,S_5,Female,33,No,No,No,No,No,22.6,5.9663,...,8.6434,9.6875,3.8072,10.2386,6.0748,4.2132,4.0894,6.0473,5.4366,6.1009

#Making Calculation for best Exercise

In [27]:
database.columns

Index(['ID', 'Gender', 'Age', 'Alchohol', 'Smoking', 'Non-Veg', 'Exercise',
       'Medication', 'BMI', 'sti_ANYB_PRE', 'sti_ANYB_POST ', 'sti_OM_PRE',
       'sti_OM_POST ', 'sti_SHA_PRE', 'sti_SHA_POST ', 'sti_MM_PRE',
       'sti_MM_POST ', 'sti_QUIT_PRE', 'sti_QUIT_POST ', 'sti_SPINE_PRE',
       'sti_SPINE_POST '],
      dtype='object')

In [33]:
sti_anyb=[]
sti_om = []
sti_mm = []
sti_QUIT = []
sti_spine = []
sti_sh = []

# cols = ['ID', 'Gender', 'Age', 'Alchohol', 'Smoking', 'Non-Veg', 'Exercise',
#        'Medication', 'BMI', 'sti_ANYB_PRE', 'sti_ANYB_POST  ', 'sti_OM_PRE',
#        'sti_OM_POST  ', 'sti_SHA_PRE', 'sti_SHA_POST  ', 'sti_MM_PRE',
#        'sti_MM_POST  ', 'sti_QUIT_PRE', 'sti_QUIT_POST  ', 'sti_SPINE_PRE',
#        'sti_SPINE_POST  ']
       
for i in range(len(database['ID'])):

    val = database['sti_ANYB_POST '][i] - database['sti_ANYB_PRE'][i]
    sti_anyb.append(val)

for i in range(len(database['ID'])):

    val = database['sti_OM_POST '][i] - database['sti_OM_PRE'][i]
    sti_om.append(val)

for i in range(len(database['ID'])):

    val = database['sti_SHA_POST '][i] - database['sti_SHA_PRE'][i]
    sti_sh.append(val)

for i in range(len(database['ID'])):

    val = database['sti_MM_POST '][i] - database['sti_MM_PRE'][i]
    sti_mm.append(val)

for i in range(len(database['ID'])):

    val = database['sti_QUIT_POST '][i] - database['sti_QUIT_PRE'][i]
    sti_QUIT.append(val)

for i in range(len(database['ID'])):

    val = database['sti_SPINE_POST '][i] - database['sti_SPINE_PRE'][i]
    sti_spine.append(val)

database['sti_Anyb'] = sti_anyb
database['sti_om'] = sti_om
database['sti_mm'] = sti_mm
database['sti_sh'] = sti_sh
database['sti_QUIT'] = sti_QUIT
database['sti_spine'] =sti_spine

In [35]:
selected_columns = ['sti_Anyb', 'sti_om', 'sti_mm','sti_sh', 'sti_QUIT', 'sti_spine']
col_dict = {'sti_Anyb':1, 'sti_om':2, 'sti_mm':3,'sti_sh':4, 'sti_QUIT':5, 'sti_spine':6}
# Function to find column number with minimum value in a row
def find_min_column(row):
    min_value = float('inf')  # Initialize min value with negative infinity
    min_column = None          # Initialize min column as None

    for column in selected_columns:
        if row[column] < min_value:
            min_value = row[column]
            min_column = column

    return col_dict[min_column]

# Apply the function to each row and store the result in a new column
database['sti_best'] = database.apply(find_min_column, axis=1)

In [37]:
database

,ID,Gender,Age,Alchohol,Smoking,Non-Veg,Exercise,Medication,BMI,sti_ANYB_PRE,...,sti_QUIT_POST,sti_SPINE_PRE,sti_SPINE_POST,sti_Anyb,sti_om,sti_mm,sti_sh,sti_QUIT,sti_spine,sti_best
0,S_1,Male,37,No,No,No,No,No,24.1,7.8831,...,6.8459,6.2798,6.9963,0.4038,-2.7466,-0.6480,1.9766,0.4603,0.7165,2
1,S_2,Male,47,No,No,No,Yes,Yes(Anxiety/B.P.),22.8,15.0502,...,17.3439,16.5494,15.0804,-2.6309,-8.6337,2.5199,5.2734,0.0293,-1.4690,2
2,S_3,Female,47,No,No,No,No,Yes(Thyroid),28.0,5.0374,...,7.3361,4.4889,7.4302,0.5014,-14.1675,1.1430,0.2751,-4.3086,2.9413,2
3,S_4,Female,35,No,No,No,No,No,27.4,6.1393,...,7.6654,3.7913,12.4440,0.4517,-1.7722,1.9138,0.1302,2.3326,8.6527,2
4,S_5,Female,33,No,No,No,No,No,22.6,5.9663,...,6.0473,5.4366,6.1009,6.2275,1.0441,-1.8616,6.4314,1.9579,0.6643,3
5,S_6,Female,45,No,No,No,No,Yes(B.P.),24.5,2.1225,...,1.8325,4.3904,10.9963,2.5443,-4.4973,-3.1415,0.6878,-8.0689,6.6059,5
6,S_7,Female,41,No,No,No,No,No,24.5,2.0351,...,4.8846,12.3274,6.6026,2.5803,-4.9936,-4.1950,-4.0279,-4.0056,-5.7248,6
7,S_8,Female,36,No,No,No,No,No,23.2,6.0318,...,6.1856,6.1531,7.0278,1.3909,1.5368,-0.6093,5.9077,-2.1847,0.8747,5
8,S_9,Female,35,No,No,Yes,No,Yes(Thyroid),25.0,8.7107,...,11.2727,12.1193,14.0353,-0.6122,2.6493,1.7081,1.2775,1.2541,1.9160,1
9,S_10,Male,38,Yes,No,Yes,No,No,25.8,5.8957,...,8.6791,7.5744,5.7084,-0.7611,3.5808,1.3702,3.0624,4.7128,-1.8660,6
10,S_11,Male,43,Yes,Yes,Yes,No,Yes,30.1,3.7483,...,22.6202,9.9775,17.8415,5.4347,15.6472,4.0996,20.6090,15.7723,7.8640,3
11,S_12,Male,39,No,No,No,Yes,Yes,25.4,5.9809,...,6.2730,7.8073,11.3509,-3.0230,-0.8740,-6.1237,-5.6751,3.5793,3.5436,3
12,S_13,Male,34,Yes,No,Yes,No,No,23.9,14.6812,...,10.2773,11.4630,12.6724,-2.0063,-0.3869,-2.0361,1.5534,1.1288,1.2094,3
13,S_14,Female,34,No,No,No,No,No,22.1,10.0113,...,14.8295,9.7210,15.3913,0.6149,0.0383,6.8525,1.0778,4.8737,5.6703,2
14,S_15,Female,29,No,No,Yes,No,No,25.7,5.5360,...,12.3537,11.3413,4.4978,-1.0442,5.1132,3.7888,0.8374,2.7070,-6.8435,6
15,S_16,Male,28,No,No,Yes,Yes,No,24.0,13.3165,...,16.5876,6.4355,8.0246,-0.7037,-3.7651,1.8317,-1.2754,-0.6872,1.5891,2
16,S_17,Male,28,No,No,Yes,No,No,24.3,7.6395,...,12.3404,21.0263,2.7317,-2.5144,-13.8086,3.6705,1.0741,4.5103,-18.2946,6
17,S_18,Male,29,No,No,Yes,Yes,No,25.0,17.6337,...,20.0253,17.5581,21.1951,3.3759,-3.1870,9.7649,2.4367,12.9754,3.6370,2
18,S_19,Male,30,No,No,Yes,No,No,24.6,11.9540,...,16.5549,14.1691,11.3531,2.1294,4.6163,1.2617,6.8372,-1.7347,-2.8160,6
19,S_20,Male,34,No,No,Yes,Yes,No,28.4,20.7462,...,18.6977,8.5253,11.7117,-5.0440,7.4158,7.2211,2.8632,14.6632,3.1864,1
20,S_21,Male,35,No,No,No,Yes,No,24.3,14.9445,...,11.2367,13.7264,4.3657,-4.7465,6.0298,12.9351,-3.0892,0.6340,-9.3607,6
21,S_22,Male,39,No,No,Yes,No,No,24.3,3.7976,...,7.1542,12.6885,8.0050,4.7043,-2.2670,-7.8696,-2.3948,-4.2563,-4.6835,3
22,S_23,Male,30,No,No,Yes,Yes,No,26.8,23.7238,...,16.0537,23.1332,11.1502,-1.7393,3.5644,-14.4049,4.2598,-0.6502,-11.9830,3
23,S_24,Male,45,No,No,Yes,No,Yes(Sugar),21.2,33.4174,...,31.8230,18.3007,25.5177,-15.7194,6.2404,2.8619,14.1739,11.5184,7.2170,1
24,S_25,Male,36,No,No,No,Yes,Yes(CIDP),23.8,13.5058,...,11.2603,4.2911,15.8631,2.8839,7.6783,0.1355,0.5719,-4.4836,11.5720,5
25,S_26,Male,28,No,No,Yes,No,No,22.0,1.7832,...,3.5862,4.1393,4.5809,3.1533,1.6163,5.0763,1.6401,-0.8323,0.4416,5
26,S_27,Male,41,No,No,No,Yes,No,20.9,12.6693,...,16.4534,8.7278,13.0102,3.5860,1.3632,2.4212,3.0402,2.9771,4.2824,2
27,S_28,Male,34,Yes,No,Yes,Yes,No,23.2,18.4107,...,12.8254,14.4788,10.9258,2.1159,5.3058,4.3857,0.5233,-2.7871,-3.5530,6
28,S_29,Male,37,No,No,Yes,Yes,No,22.3,11.6349,...,20.0633,10.7840,15.6743,4.1029,-5.8636,-1.6533,-9.7326,4.8831,4.8903,4
29,S_30,Female,29,No,No,Yes,No,No,25.4,16.5768,...,19.0087,18.8422,21.1505,1.7528,4.3876,-0.3890,2.1093,-0.6150,2.3083,5
30,S_31,Female,39,No,No,Yes,No,No,27.5,5.5726,...,4.2405,7.3131,4.5603,-0.0250,-5.7596,-8.0799,-0.0552,-8.4905,-2.7528,5
31,S_32,Female,34,No,No,Yes,No,No,18.8,6.1671,...,3.0915,10.5236,4.3675,2.6761,-0.6398,-2.5045,-7.6826,-9.8803,-6.1561,5
32,S_33,Female,40,No,No,No,Yes,No,19.6,13.1615,...,12.8018,14.9919,8.7215,-7.8208,-16.2346,2.9147,-4.5677,-8.9561,-6.2704,2
33,S_34,Female,29,No,No,Yes,No,No,19.0,10.7000,...,11.6000,11.3000,10.4000,0.2000,-0.5000,-0.1000,-0.1000,0.5000,-0.9000,6
34,S_35,Male,28,Yes,No,No,Yes,No,22.7,3.8722,...,19.1287,9.6645,8.5479,17.0118,-1.1194,1.2499,-7.9155,7.8645,-1.1166,4
35,S_36,Male,28,No,No,Yes,No,No,18.9,9.7372,...,7.9076,12.3275,8.6200,-0.8190,-0.3560,0.6565,-6.1067,-5.5242,-3.7075,4
36,S_37,Male,34,Yes,No,No,No,No,22.3,16.0434,...,16.7412,15.7151,3.4044,-9.4443,-2.7784,-0.0290,-8.3822,0.8921,-12.3107,6
37,S_38,Female,31,Yes,No,No,No,No,22.4,8.6972,...,3.4364,7.3349,4.5297,-2.0580,2.6943,-0.4722,0.7002,-9.8330,-2.8052,5
38,S_39,Male,39,Yes,No,Yes,Yes,Yes(Gas),22.1,10.7000,...,11.6000,11.3000,10.4000,0.2000,-0.5000,-0.1000,-0.1000,0.5000,-0.9000,6
39,S_40,Male,39,No,No,Yes,No,No,28.1,15.0219,...,23.2583,22.4633,22.7594,5.3072,-1.3761,1.5406,-9.5569,2.6628,0.2961,4
40,S_41,Female,37,No,No,Yes,No,No,31.4,31.5419,...,12.6689,30.2995,15.8997,-17.9319,-7.8112,-4.0064,3.4039,-16.6492,-14.3998,1
41,S_42,Female,43,No,No,No,Yes,No,26.5,15.9281,...,9.1530,5.1093,13.2107,11.0419,-13.0576,1.2946,-26.6927,0.6411,8.1014,4
42,S_43,Male,28,Yes,Yes,Yes,No,No,18.7,7.4180,...,8.8492,10.5530,9.3591,2.4412,2.4412,-3.0659,1.4515,-0.3788,-1.1939,3
43,S_44,Male,28,No,No,Yes,No,No,24.1,4.0680,...,12.8024,14.0480,13.7403,7.9555,4.4131,-0.2959,6.2979,1.7156,-0.3077,6
44,S_45,Male,31,No,No,No,Yes,No,26.9,6.0800,...,13.9539,15.3387,14.0547,8.2683,-10.9771,7.3734,0.3234,6.0960,-1.2840,2
45,S_46,Female,28,No,No,Yes,Yes,No,26.0,6.3040,...,2.2862,5.5071,1.7306,-2.7388,-2.3637,-5.0292,-5.2996,-2.3871,-3.7765,4
46,S_47,Female,30,No,No,No,No,No,31.9,8.3855,...,13.1908,8.7267,10.9552,0.4468,2.7653,1.2912,3.7014,5.2981,2.2285,1
47,S_48,Male,36,Yes,No,Yes,Yes,Yes(B.P.),33.1,11.8855,...,6.3230,5.3079,3.3848,-4.9831,2.5729,4.2058,1.7492,1.7959,-1.9231,1
48,S_49,Female,28,No,No,Yes,Yes,Yes,22.6,13.0756,...,8.7123,13.2597,9.1003,-3.5029,4.8500,-5.5401,-1.1994,-1.5955,-4.1594,3
49,S_50,Male,37,No,No,No,No,Yes,23.8,4.2742,...,9.2930,2.7995,2.9775,0.5300,1.1329,-3.7634,0.9225,4.9786,0.1780,3
50,S_51,Male,28,No,No,No,Yes,No,27.9,5.0178,...,5.1314,2.0380,2.3531,-1.7477,4.4382,-3.7756,-1.6398,2.7018,0.3151,3
51,S_52,Male,30,No,No,No,Yes,No,22.7,4.4641,...,4.9820,10.1428,6.3424,-2.1190,-5.7920,-5.0067,-2.6078,-1.3682,-3.8004,2
52,S_53,Male,29,No,No,No,No,No,20.9,3.1714,...,4.4918,7.5769,8.0512,1.1873,0.5824,-1.9170,-1.6331,-4.7774,0.4743,5
53,S_54,Male,31,No,No,Yes,Yes,No,19.8,26.5490,...,15.5165,25.1781,23.3867,-4.6386,2.4582,-6.6464,1.2179,0.8698,-1.7914,3
54,S_55,Male,30,No,No,Yes,No,No,29.0,16.2933,...,19.0972,6.6616,5.6043,1.6378,0.5368,-2.2699,9.3096,-2.8015,-1.0573,5
55,S_56,Male,31,No,No,No,Yes,No,19.5,17.4633,...,13.0986,11.6870,13.2495,-10.9000,-1.5480,-0.2634,-5.0767,8.1224,1.5625,1
56,S_57,Male,34,No,No,Yes,Yes,No,18.9,6.1567,...,9.6567,13.9726,8.9834,1.5811,2.7160,-1.8054,-6.3642,3.4359,-4.9892,4
57,S_58,Male,28,Yes,No,Yes,No,No,27.7,7.9939,...,13.8127,20.0417,13.5193,12.5407,-0.6362,-0.3084,-2.5216,-2.0937,-6.5224,6

In [38]:
y = database['sti_best']
y.value_counts()

6    12
2    11
3    11
5    10
1     7
4     7
Name: sti_best, dtype: int64

In [36]:
database.columns

Index(['ID', 'Gender', 'Age', 'Alchohol', 'Smoking', 'Non-Veg', 'Exercise',
       'Medication', 'BMI', 'sti_ANYB_PRE', 'sti_ANYB_POST ', 'sti_OM_PRE',
       'sti_OM_POST ', 'sti_SHA_PRE', 'sti_SHA_POST ', 'sti_MM_PRE',
       'sti_MM_POST ', 'sti_QUIT_PRE', 'sti_QUIT_POST ', 'sti_SPINE_PRE',
       'sti_SPINE_POST ', 'sti_Anyb', 'sti_om', 'sti_mm', 'sti_sh', 'sti_QUIT',
       'sti_spine', 'sti_best'],
      dtype='object')

In [39]:
drop_cols = ['sti_ANYB_PRE', 'sti_ANYB_POST ', 'sti_OM_PRE',
       'sti_OM_POST ', 'sti_SHA_PRE', 'sti_SHA_POST ', 'sti_MM_PRE',
       'sti_MM_POST ', 'sti_QUIT_PRE', 'sti_QUIT_POST ', 'sti_SPINE_PRE',
       'sti_SPINE_POST ', 'sti_Anyb', 'sti_om', 'sti_mm', 'sti_sh', 'sti_QUIT',
       'sti_spine']
database=database.drop(drop_cols,axis=1)

In [40]:
database

,ID,Gender,Age,Alchohol,Smoking,Non-Veg,Exercise,Medication,BMI,sti_best
0,S_1,Male,37,No,No,No,No,No,24.1,2
1,S_2,Male,47,No,No,No,Yes,Yes(Anxiety/B.P.),22.8,2
2,S_3,Female,47,No,No,No,No,Yes(Thyroid),28.0,2
3,S_4,Female,35,No,No,No,No,No,27.4,2
4,S_5,Female,33,No,No,No,No,No,22.6,3
5,S_6,Female,45,No,No,No,No,Yes(B.P.),24.5,5
6,S_7,Female,41,No,No,No,No,No,24.5,6
7,S_8,Female,36,No,No,No,No,No,23.2,5
8,S_9,Female,35,No,No,Yes,No,Yes(Thyroid),25.0,1
9,S_10,Male,38,Yes,No,Yes,No,No,25.8,6
10,S_11,Male,43,Yes,Yes,Yes,No,Yes,30.1,3
11,S_12,Male,39,No,No,No,Yes,Yes,25.4,3
12,S_13,Male,34,Yes,No,Yes,No,No,23.9,3
13,S_14,Female,34,No,No,No,No,No,22.1,2
14,S_15,Female,29,No,No,Yes,No,No,25.7,6
15,S_16,Male,28,No,No,Yes,Yes,No,24.0,2
16,S_17,Male,28,No,No,Yes,No,No,24.3,6
17,S_18,Male,29,No,No,Yes,Yes,No,25.0,2
18,S_19,Male,30,No,No,Yes,No,No,24.6,6
19,S_20,Male,34,No,No,Yes,Yes,No,28.4,1
20,S_21,Male,35,No,No,No,Yes,No,24.3,6
21,S_22,Male,39,No,No,Yes,No,No,24.3,3
22,S_23,Male,30,No,No,Yes,Yes,No,26.8,3
23,S_24,Male,45,No,No,Yes,No,Yes(Sugar),21.2,1
24,S_25,Male,36,No,No,No,Yes,Yes(CIDP),23.8,5
25,S_26,Male,28,No,No,Yes,No,No,22.0,5
26,S_27,Male,41,No,No,No,Yes,No,20.9,2
27,S_28,Male,34,Yes,No,Yes,Yes,No,23.2,6
28,S_29,Male,37,No,No,Yes,Yes,No,22.3,4
29,S_30,Female,29,No,No,Yes,No,No,25.4,5
30,S_31,Female,39,No,No,Yes,No,No,27.5,5
31,S_32,Female,34,No,No,Yes,No,No,18.8,5
32,S_33,Female,40,No,No,No,Yes,No,19.6,2
33,S_34,Female,29,No,No,Yes,No,No,19.0,6
34,S_35,Male,28,Yes,No,No,Yes,No,22.7,4
35,S_36,Male,28,No,No,Yes,No,No,18.9,4
36,S_37,Male,34,Yes,No,No,No,No,22.3,6
37,S_38,Female,31,Yes,No,No,No,No,22.4,5
38,S_39,Male,39,Yes,No,Yes,Yes,Yes(Gas),22.1,6
39,S_40,Male,39,No,No,Yes,No,No,28.1,4
40,S_41,Female,37,No,No,Yes,No,No,31.4,1
41,S_42,Female,43,No,No,No,Yes,No,26.5,4
42,S_43,Male,28,Yes,Yes,Yes,No,No,18.7,3
43,S_44,Male,28,No,No,Yes,No,No,24.1,6
44,S_45,Male,31,No,No,No,Yes,No,26.9,2
45,S_46,Female,28,No,No,Yes,Yes,No,26.0,4
46,S_47,Female,30,No,No,No,No,No,31.9,1
47,S_48,Male,36,Yes,No,Yes,Yes,Yes(B.P.),33.1,1
48,S_49,Female,28,No,No,Yes,Yes,Yes,22.6,3
49,S_50,Male,37,No,No,No,No,Yes,23.8,3
50,S_51,Male,28,No,No,No,Yes,No,27.9,3
51,S_52,Male,30,No,No,No,Yes,No,22.7,2
52,S_53,Male,29,No,No,No,No,No,20.9,5
53,S_54,Male,31,No,No,Yes,Yes,No,19.8,3
54,S_55,Male,30,No,No,Yes,No,No,29.0,5
55,S_56,Male,31,No,No,No,Yes,No,19.5,1
56,S_57,Male,34,No,No,Yes,Yes,No,18.9,4
57,S_58,Male,28,Yes,No,Yes,No,No,27.7,6

In [41]:
database.to_csv('final_data_STI.csv',index=False)